

const sauvegarde = [{
    _id: ObjectId("6372a1e4fd50a5c4ac0d441d"),
    group: 'A',
    nomEquipeA: 'A',
    nomEquipeB: 'B',
    joueursEquipeA: [ 'lucas', 'enzo' ],
    joueursEquipeB: [ 'batiste', 'mathias' ],
    scoreEquipeA: 2,
    scoreEquipeB: 1,
    coteEquipeA: 1.12,
    coteEquipeB: 1.8,
    ligue: 'parisienne',
    round: 'groupStage',
    type: 'match',
    updatedAt: ISODate("2022-11-18T00:23:10.985Z"),
    finalScoreEquipeA: 1,
    finalScoreEquipeB: 2,
    live: 'closed',
    arrayVictoireEquipePrediction: [ 'B', 'A', 'B', 'A', 'A' ],
    usersBet: [ '63769d01f47d3bb4cd2555ed' ]
  },
  {
    _id: ObjectId("6372a1e4fd50a5c4ac0d441e"),
    group: 'A',
    nomEquipeA: 'A',
    nomEquipeB: 'B',
    joueursEquipeA: [ 'lucas', 'enzo' ],
    joueursEquipeB: [ 'batiste', 'mathias' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 9,
    coteEquipeB: 1,
    ligue: 'parisienne',
    round: 'groupStage',
    type: 'match',
    updatedAt: ISODate("2022-11-17T21:43:34.472Z"),
    finalScoreEquipeA: 4,
    finalScoreEquipeB: 2,
    live: 'closed',
    arrayVictoireEquipePrediction: [ 'B', 'A', 'A' ],
    usersBet: [ '6372cf559287f5c14c86f554', '63769d01f47d3bb4cd2555ed' ]
  },
  {
    _id: ObjectId("6372a1e4fd50a5c4ac0d441f"),
    group: 'A',
    nomEquipeA: [ 'C' ],
    nomEquipeB: [ 'D' ],
    joueursEquipeA: [ 'lucas', 'uuuuuuuuu' ],
    joueursEquipeB: [ 'batiste', 'vvvv' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 1.2,
    coteEquipeB: 1.4,
    ligue: 'parisienne',
    round: 'groupStage',
    type: 'match',
    updatedAt: ISODate("2022-11-17T21:43:52.869Z"),
    arrayVictoireEquipePrediction: [ 'B', 'B', 'B', 'B' ],
    usersBet: [ '6372cf559287f5c14c86f554', '63769d01f47d3bb4cd2555ed' ],
    finalScoreEquipeA: 1,
    finalScoreEquipeB: 5,
    live: 'closed'
  },
  {
    _id: ObjectId("6372a1e4fd50a5c4ac0d4420"),
    group: 'A',
    nomEquipeA: [ 'D' ],
    nomEquipeB: [ 'Z' ],
    joueursEquipeA: [ 'ddd', 'enzo' ],
    joueursEquipeB: [ 'batiste', 'maccthias' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 1.3,
    coteEquipeB: 1.6,
    ligue: 'parisienne',
    round: 'groupStage',
    type: 'match',
    updatedAt: ISODate("2022-11-17T01:23:55.694Z"),
    arrayVictoireEquipePrediction: [ 'B', 'B' ],
    usersBet: [ '6372cf559287f5c14c86f554' ],
    finalScoreEquipeB: 3,
    live: 'closed',
    finalScoreEquipeA: 5
  },
  {
    _id: ObjectId("6374f9242f54b9fa9038b293"),
    ligue: 'Ligue Parisienne',
    type: 'match',
    round: 'Poulle Mouillée',
    group: 'groupe A',
    nomEquipeA: 'Les mystiques',
    nomEquipeB: 'Badger Hunter',
    joueursEquipeA: [ 'Tristan Prouteau', 'Jerome renimel' ],
    joueursEquipeB: [ 'Aymeric Sandoz', 'Erwan Chapelière' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 79,
    coteEquipeB: 21,
    arrayVictoireEquipePrediction: [
      'B', 'B', 'B', 'B',
      'B', 'B', 'A', 'B',
      'A', 'A'
    ],
    updatedAt: ISODate("2022-11-17T01:56:46.297Z"),
    usersBet: [ '6372cf559287f5c14c86f554' ],
    finalScoreEquipeA: 4,
    finalScoreEquipeB: 2,
    live: 'closed'
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc657"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poulpe',
    nomEquipeA: 'Mothercuter',
    nomEquipeB: 'Velouté Tactique',
    joueursEquipeA: [ 'Paul Halphen', 'Sebastien Lawrence' ],
    joueursEquipeB: [ 'Louis Durand', 'Théo Vanh Hemelryck' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 65,
    coteEquipeB: 35
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc658"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poulpe',
    nomEquipeA: 'Mothercuter',
    nomEquipeB: 'Pas Dégeu',
    joueursEquipeA: [ 'Paul Halphen', 'Sebastien Lawrence' ],
    joueursEquipeB: [ 'Louis Durand', 'Théo Vanh Hemelryck' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 65,
    coteEquipeB: 35
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc659"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poulpe',
    nomEquipeA: 'Velouté Tactique',
    nomEquipeB: 'Pas Dégeu',
    joueursEquipeA: [ 'Benoît Durand', 'Ryan Danekas' ],
    joueursEquipeB: [ 'Louis Durand', 'Théo Vanh Hemelryck' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 45,
    coteEquipeB: 55
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc65a"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poule au Pot',
    nomEquipeA: 'Les Fisheurs',
    nomEquipeB: 'Double Facture',
    joueursEquipeA: [ 'Ulysse Couturier', 'Pierre Hachard' ],
    joueursEquipeB: [ 'Alexis Picard', 'Clément Martin' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 35,
    coteEquipeB: 65
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc65b"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poule au Pot',
    nomEquipeA: 'On déteste Clément',
    nomEquipeB: 'Les Fisheurs',
    joueursEquipeA: [ 'Basile Vittrai', 'Faustin Dubois' ],
    joueursEquipeB: [ 'Ulysse Couturier', 'Pierre Hachard' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 35,
    coteEquipeB: 65
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc65c"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poule au Pot',
    nomEquipeA: 'On déteste Clément',
    nomEquipeB: 'Double Facture',
    joueursEquipeA: [ 'Basile Vittrai', 'Faustin Dubois' ],
    joueursEquipeB: [ 'Alexis Picard', 'Clément Martin' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 30,
    coteEquipeB: 70
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc65d"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poule au Pot',
    nomEquipeA: 'Roundnet Orléans',
    nomEquipeB: 'Double Facture',
    joueursEquipeA: [ 'Aymeric Sandoz', 'Erwan Chapelière' ],
    joueursEquipeB: [ 'Alexis Picard', 'Clément Martin' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 99,
    coteEquipeB: 1
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc65e"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poule au Pot',
    nomEquipeA: 'Roundnet Orléans',
    nomEquipeB: 'On déteste Clément',
    joueursEquipeA: [ 'Aymeric Sandoz', 'Erwan Chapelière' ],
    joueursEquipeB: [ 'Basile Vittrai', 'Faustin Dubois' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 99,
    coteEquipeB: 1
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc65f"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poule au Pot',
    nomEquipeA: 'Roundnet Orléans',
    nomEquipeB: 'Les Fisheurs',
    joueursEquipeA: [ 'Aymeric Sandoz', 'Erwan Chapelière' ],
    joueursEquipeB: [ 'Ulysse Couturier', 'Pierre Hachard' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 99,
    coteEquipeB: 1
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc660"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poule Mouillée',
    nomEquipeA: 'David & Goliath',
    nomEquipeB: 'Les Kabass',
    joueursEquipeA: [ 'Fabien Devaud', 'Timothé Boulet' ],
    joueursEquipeB: [ 'Thibault Brun', 'Benjamin Létang' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 50,
    coteEquipeB: 50
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc661"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poule Mouillée',
    nomEquipeA: 'Bad Salmons',
    nomEquipeB: 'Les Kabass',
    joueursEquipeA: [ 'Pierre Lecrosnier', 'Anaïs Duport' ],
    joueursEquipeB: [ 'Thibault Brun', 'Benjamin Létang' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 50,
    coteEquipeB: 50
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc662"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poule Mouillée',
    nomEquipeA: 'Bad Salmons',
    nomEquipeB: 'David & Goliath',
    joueursEquipeA: [ 'Pierre Lecrosnier', 'Anaïs Duport' ],
    joueursEquipeB: [ 'Fabien Devaud', 'Timothé Boulet' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 50,
    coteEquipeB: 50
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc663"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poule Pondeuse',
    nomEquipeA: 'Goffa Lolita',
    nomEquipeB: ' Jupikai',
    joueursEquipeA: [ 'Lancelot Touzé', 'Benoît Nguyen' ],
    joueursEquipeB: [ 'Pierre Buttet', 'Julien Blanchard' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 50,
    coteEquipeB: 50
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc664"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poule Pondeuse',
    nomEquipeA: 'Les mystiques',
    nomEquipeB: ' Jupikai',
    joueursEquipeA: [ 'Tristan Prouteau', 'Jerome Renimel' ],
    joueursEquipeB: [ 'Pierre Buttet', 'Julien Blanchard' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 70,
    coteEquipeB: 30
  },
  {
    _id: ObjectId("6376ca5dca888cce0a5cc665"),
    ligue: 'ligue_Parisienne',
    type: 'match',
    round: 'GroupStage',
    group: 'Poule Pondeuse',
    nomEquipeA: 'Les mystiques',
    nomEquipeB: ' Jupikai',
    joueursEquipeA: [ 'Tristan Prouteau', 'Jerome Renimel' ],
    joueursEquipeB: [ 'Pierre Buttet', 'Julien Blanchard' ],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 70,
    coteEquipeB: 30
  }
]