const ligueParisienne = [
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poulpe",
    nomEquipeA: "Mothercuter",
    nomEquipeB: "Velouté Tactique",
    joueursEquipeA: ["Paul Halphen", "Sebastien Lawrence"],
    joueursEquipeB: ["Louis Durand", "Théo Vanh Hemelryck"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 65,
    coteEquipeB: 35,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poulpe",
    nomEquipeA: "Mothercuter",
    nomEquipeB: "Pas Dégeu",
    joueursEquipeA: ["Paul Halphen", "Sebastien Lawrence"],
    joueursEquipeB: ["Louis Durand", "Théo Vanh Hemelryck"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 65,
    coteEquipeB: 35,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poulpe",
    nomEquipeA: "Velouté Tactique",
    nomEquipeB: "Pas Dégeu",
    joueursEquipeA: ["Benoît Durand", "Ryan Danekas"],
    joueursEquipeB: ["Louis Durand", "Théo Vanh Hemelryck"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 45,
    coteEquipeB: 55,
  },

  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule au Pot",
    nomEquipeA: "Les Fisheurs",
    nomEquipeB: "Double Facture",
    joueursEquipeA: ["Ulysse Couturier", "Pierre Hachard"],
    joueursEquipeB: ["Alexis Picard", "Clément Martin"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 35,
    coteEquipeB: 65,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule au Pot",
    nomEquipeA: "On déteste Clément",
    nomEquipeB: "Les Fisheurs",
    joueursEquipeA: ["Basile Vittrai", "Faustin Dubois"],
    joueursEquipeB: ["Ulysse Couturier", "Pierre Hachard"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 35,
    coteEquipeB: 65,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule au Pot",
    nomEquipeA: "On déteste Clément",
    nomEquipeB: "Double Facture",
    joueursEquipeA: ["Basile Vittrai", "Faustin Dubois"],
    joueursEquipeB: ["Alexis Picard", "Clément Martin"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 30,
    coteEquipeB: 70,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule au Pot",
    nomEquipeA: "Roundnet Orléans",
    nomEquipeB: "Double Facture",
    joueursEquipeA: ["Aymeric Sandoz", "Erwan Chapelière"],
    joueursEquipeB: ["Alexis Picard", "Clément Martin"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 99,
    coteEquipeB: 1,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule au Pot",
    nomEquipeA: "Roundnet Orléans",
    nomEquipeB: "On déteste Clément",
    joueursEquipeA: ["Aymeric Sandoz", "Erwan Chapelière"],
    joueursEquipeB: ["Basile Vittrai", "Faustin Dubois"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 99,
    coteEquipeB: 1,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule au Pot",
    nomEquipeA: "Roundnet Orléans",
    nomEquipeB: "Les Fisheurs",
    joueursEquipeA: ["Aymeric Sandoz", "Erwan Chapelière"],
    joueursEquipeB: ["Ulysse Couturier", "Pierre Hachard"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 99,
    coteEquipeB: 1,
  },

  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Mouillée",
    nomEquipeA: "David & Goliath",
    nomEquipeB: "Les Kabass",
    joueursEquipeA: ["Fabien Devaud", "Timothé Boulet"],
    joueursEquipeB: ["Thibault Brun", "Benjamin Létang"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 50,
    coteEquipeB: 50,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Mouillée",
    nomEquipeA: "Bad Salmons",
    nomEquipeB: "Les Kabass",
    joueursEquipeA: ["Pierre Lecrosnier", "Anaïs Duport"],
    joueursEquipeB: ["Thibault Brun", "Benjamin Létang"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 50,
    coteEquipeB: 50,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Mouillée",
    nomEquipeA: "Bad Salmons",
    nomEquipeB: "David & Goliath",
    joueursEquipeA: ["Pierre Lecrosnier", "Anaïs Duport"],
    joueursEquipeB: ["Fabien Devaud", "Timothé Boulet"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 50,
    coteEquipeB: 50,
  },

  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Pondeuse",
    nomEquipeA: "Goffa Lolita",
    nomEquipeB: " Jupikai",
    joueursEquipeA: ["Lancelot Touzé", "Benoît Nguyen"],
    joueursEquipeB: ["Pierre Buttet", "Julien Blanchard"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 50,
    coteEquipeB: 50,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Pondeuse",
    nomEquipeA: "Les mystiques",
    nomEquipeB: " Jupikai",
    joueursEquipeA: ["Tristan Prouteau", "Jerome Renimel"],
    joueursEquipeB: ["Pierre Buttet", "Julien Blanchard"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 70,
    coteEquipeB: 30,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Pondeuse",
    nomEquipeA: "Les mystiques",
    nomEquipeB: " Jupikai",
    joueursEquipeA: ["Tristan Prouteau", "Jerome Renimel"],
    joueursEquipeB: ["Pierre Buttet", "Julien Blanchard"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 70,
    coteEquipeB: 30,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Pondeuse",
    nomEquipeA: "Les mystiques",
    nomEquipeB: "Goffa Lolita",
    joueursEquipeA: ["Tristan Prouteau", "Jerome Renimel"],
    joueursEquipeB: ["Lancelot Touzé", "Benoît Nguyen"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 70,
    coteEquipeB: 30,
  },
  //////fake
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Mouillée",
    nomEquipeA: "Les mystiques",
    nomEquipeB: "Badger Hunter",
    joueursEquipeA: ["Tristan Prouteau", "Jerome renimel"],
    joueursEquipeB: ["Aymeric Sandoz", "Erwan Chapelière"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 5,
    coteEquipeB: 2,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "group",
    group: "A",
    nomEquipeA: "A",
    nomEquipeB: "B",
    joueursEquipeA: ["lucas", "enzo"],
    joueursEquipeB: ["batiste", "mathias"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 5,
    coteEquipeB: 2,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "group",
    group: "A",
    nomEquipeA: "A",
    nomEquipeB: "B",
    joueursEquipeA: ["lucas", "enzo"],
    joueursEquipeB: ["batiste", "mathias"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 9,
    coteEquipeB: 1,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "group",
    group: "A",
    nomEquipeA: "C",
    nomEquipeB: "D",
    joueursEquipeA: ["lucas", "uuuuuuuuu"],
    joueursEquipeB: ["batiste", "vvvv"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 1.2,
    coteEquipeB: 1.4,
  },
  {
    ligue: "ligue_Parisienne",
    type: "match",
    round: "group",
    group: "A",
    nomEquipeA: "D",
    nomEquipeB: "Z",
    joueursEquipeA: ["ddd", "enzo"],
    joueursEquipeB: ["batiste", "maccthias"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 1.3,
    coteEquipeB: 1.6,
  },
];

exports.find = () => {
  return new Promise((resolve, reject) =>
    resolve(JSON.parse(JSON.stringify(ligueParisienne)))
  );
};

exports.findByGroup = (group) => {
  return new Promise((resolve, reject) =>
    resolve(
      JSON.parse(JSON.stringify(ligueParisienne)).find(
        (ligueParisienne) => ligueParisienne.group == group
      )
    )
  );
};
