const autres = [
  {
    ligue: "autre",
    type: "autre",
    round: "",
    group: "",
    bet: "Erwan lâche un sourire en compétition en 2023",
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 4.1,
    coteEquipeB: 1.6,
    live: "open",
  },
  {
    type: "autre",
    bet: "Erwan lâche un sourire en compétition en 2023",

    answer1: "Vrai",
    answer2: "Faux",

    coteAnswer1: 1,
    coteAnswer2: 1,
    live: "open",
  },
];

const ligueParisienne = [
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poulpe",
    nomEquipeA: "TG",
    nomEquipeB: "Mothercuter",
    joueursEquipeA: ["Gabriel Chamoulaud", "Thomas Vicaire"],
    joueursEquipeB: ["Paul Halphen", "Sebastien Lawrence"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 4.1,
    coteEquipeB: 1.6,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poulpe",
    nomEquipeA: "TG",
    nomEquipeB: "Pas Dégueu",
    joueursEquipeA: ["Gabriel Chamoulaud", "Thomas Vicaire"],
    joueursEquipeB: ["Louis Durand", "Théo Vanh Hemelryck"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 4.1,
    coteEquipeB: 1.6,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poulpe",
    nomEquipeA: "TG",
    nomEquipeB: "Velouté Tactique",
    joueursEquipeA: ["Gabriel Chamoulaud", "Thomas Vicaire"],
    joueursEquipeB: ["Benoît Durand", "Ryan Danekas"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 4.1,
    coteEquipeB: 1.6,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poulpe",
    nomEquipeA: "Mothercuter",
    nomEquipeB: "Velouté Tactique",
    joueursEquipeA: ["Paul Halphen", "Sebastien Lawrence"],
    joueursEquipeB: ["Benoît Durand", "Ryan Danekas"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 4.1,
    coteEquipeB: 1.6,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poulpe",
    nomEquipeA: "Mothercuter",
    nomEquipeB: "Pas Dégeu",
    joueursEquipeA: ["Paul Halphen", "Sebastien Lawrence"],
    joueursEquipeB: ["Louis Durand", "Théo Vanh Hemelryck"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 2.7,
    coteEquipeB: 1.8,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poulpe",
    nomEquipeA: "Velouté Tactique",
    nomEquipeB: "Pas Dégeu",
    joueursEquipeA: ["Benoît Durand", "Ryan Danekas"],
    joueursEquipeB: ["Louis Durand", "Théo Vanh Hemelryck"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 2.1,
    coteEquipeB: 2.9,
    live: "open",
  },

  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule au Pot",
    nomEquipeA: "Les Fisheurs",
    nomEquipeB: "Double Facture",
    joueursEquipeA: ["Ulysse Couturier", "Pierre Hachard"],
    joueursEquipeB: ["Alexis Picard", "Clément Martin"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 1.9,
    coteEquipeB: 2.7,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule au Pot",
    nomEquipeA: "On déteste Clément",
    nomEquipeB: "Les Fisheurs",
    joueursEquipeA: ["Basile Vittrai", "Faustin Dubois"],
    joueursEquipeB: ["Ulysse Couturier", "Pierre Hachard"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 3.9,
    coteEquipeB: 1.9,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule au Pot",
    nomEquipeA: "On déteste Clément",
    nomEquipeB: "Double Facture",
    joueursEquipeA: ["Basile Vittrai", "Faustin Dubois"],
    joueursEquipeB: ["Alexis Picard", "Clément Martin"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 2.1,
    coteEquipeB: 2.7,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule au Pot",
    nomEquipeA: "Roundnet Orléans",
    nomEquipeB: "Double Facture",
    joueursEquipeA: ["Aymeric Sandoz", "Erwan Chapelière"],
    joueursEquipeB: ["Alexis Picard", "Clément Martin"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 1.2,
    coteEquipeB: 15,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule au Pot",
    nomEquipeA: "Roundnet Orléans",
    nomEquipeB: "On déteste Clément",
    joueursEquipeA: ["Aymeric Sandoz", "Erwan Chapelière"],
    joueursEquipeB: ["Basile Vittrai", "Faustin Dubois"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 1.3,
    coteEquipeB: 14,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule au Pot",
    nomEquipeA: "Roundnet Orléans",
    nomEquipeB: "Les Fisheurs",
    joueursEquipeA: ["Aymeric Sandoz", "Erwan Chapelière"],
    joueursEquipeB: ["Ulysse Couturier", "Pierre Hachard"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 1.4,
    coteEquipeB: 13,
    live: "open",
  },

  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Mouillée",
    nomEquipeA: "David & Goliath",
    nomEquipeB: "Les Kabass",
    joueursEquipeA: ["Fabien Devaud", "Timothé Boulet"],
    joueursEquipeB: ["Thibault Brun", "Benjamin Létang"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 2.5,
    coteEquipeB: 2.1,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Mouillée",
    nomEquipeA: "Bad Salmons",
    nomEquipeB: "Les Kabass",
    joueursEquipeA: ["Pierre Lecrosnier", "Anaïs Duport"],
    joueursEquipeB: ["Thibault Brun", "Benjamin Létang"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 1.9,
    coteEquipeB: 3.1,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Mouillée",
    nomEquipeA: "Bad Salmons",
    nomEquipeB: "David & Goliath",
    joueursEquipeA: ["Pierre Lecrosnier", "Anaïs Duport"],
    joueursEquipeB: ["Fabien Devaud", "Timothé Boulet"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 1.8,
    coteEquipeB: 3.3,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Mouillée",
    nomEquipeA: "Bad Salmons",
    nomEquipeB: "Les Kabass",
    joueursEquipeA: ["Pierre Lecrosnier", "Anaïs Duport"],
    joueursEquipeB: ["Thibault Brun", "Benjamin Létang"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 1.7,
    coteEquipeB: 3.4,
    live: "open",
  },

  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Pondeuse",
    nomEquipeA: "Goffa Lolita",
    nomEquipeB: " Jupikai",
    joueursEquipeA: ["Lancelot Touzé", "Benoît Nguyen"],
    joueursEquipeB: ["Pierre Buttet", "Julien Blanchard"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 2.5,
    coteEquipeB: 2.4,
    live: "open",
  },

  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Pondeuse",
    nomEquipeA: "Les mystiques",
    nomEquipeB: " Jupikai",
    joueursEquipeA: ["Tristan Prouteau", "Jerome Renimel"],
    joueursEquipeB: ["Pierre Buttet", "Julien Blanchard"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 2.99,
    coteEquipeB: 1.78,
    live: "open",
  },
  {
    ligue: "Ligue Parisienne",
    type: "match",
    round: "GroupStage",
    group: "Poule Pondeuse",
    nomEquipeA: "Les mystiques",
    nomEquipeB: "Goffa Lolita",
    joueursEquipeA: ["Tristan Prouteau", "Jerome Renimel"],
    joueursEquipeB: ["Lancelot Touzé", "Benoît Nguyen"],
    scoreEquipeA: {},
    scoreEquipeB: {},
    coteEquipeA: 2.11,
    coteEquipeB: 1.7,
    live: "open",
  },
  //////fake
  // {
  //   ligue: "Ligue Parisienne",
  //   type: "match",
  //   round: "GroupStage",
  //   group: "Poule Mouillée",
  //   nomEquipeA: "Les mystiques",
  //   nomEquipeB: "Badger Hunter",
  //   joueursEquipeA: ["Tristan Prouteau", "Jerome renimel"],
  //   joueursEquipeB: ["Aymeric Sandoz", "Erwan Chapelière"],
  //   scoreEquipeA: {},
  //   scoreEquipeB: {},
  //   coteEquipeA: 5,
  //   coteEquipeB: 2,
  // },
  // {
  //   ligue: "Ligue Parisienne",
  //   type: "match",
  //   round: "group",
  //   group: "A",
  //   nomEquipeA: "A",
  //   nomEquipeB: "B",
  //   joueursEquipeA: ["lucas", "enzo"],
  //   joueursEquipeB: ["batiste", "mathias"],
  //   scoreEquipeA: {},
  //   scoreEquipeB: {},
  //   coteEquipeA: 5,
  //   coteEquipeB: 2,
  // },
  // {
  //   ligue: "Ligue Parisienne",
  //   type: "match",
  //   round: "group",
  //   group: "A",
  //   nomEquipeA: "A",
  //   nomEquipeB: "B",
  //   joueursEquipeA: ["lucas", "enzo"],
  //   joueursEquipeB: ["batiste", "mathias"],
  //   scoreEquipeA: {},
  //   scoreEquipeB: {},
  //   coteEquipeA: 9,
  //   coteEquipeB: 1,
  // },
  // {
  //   ligue: "Ligue Parisienne",
  //   type: "match",
  //   round: "group",
  //   group: "A",
  //   nomEquipeA: "C",
  //   nomEquipeB: "D",
  //   joueursEquipeA: ["lucas", "uuuuuuuuu"],
  //   joueursEquipeB: ["batiste", "vvvv"],
  //   scoreEquipeA: {},
  //   scoreEquipeB: {},
  //   coteEquipeA: 1.2,
  //   coteEquipeB: 1.4,
  // },
  // {
  //   ligue: "Ligue Parisienne",
  //   type: "match",
  //   round: "group",
  //   group: "A",
  //   nomEquipeA: "D",
  //   nomEquipeB: "Z",
  //   joueursEquipeA: ["ddd", "enzo"],
  //   joueursEquipeB: ["batiste", "maccthias"],
  //   scoreEquipeA: {},
  //   scoreEquipeB: {},
  //   coteEquipeA: 1.3,
  //   coteEquipeB: 1.6,
  // },
];

// exports.find = () => {
//   return new Promise((resolve, reject) =>
//     resolve(JSON.parse(JSON.stringify(ligueParisienne)))
//   );
// };

// exports.findByGroup = (group) => {
//   return new Promise((resolve, reject) =>
//     resolve(
//       JSON.parse(JSON.stringify(ligueParisienne)).find(
//         (ligueParisienne) => ligueParisienne.group == group
//       )
//     )
//   );
// };
